// export const KEYWORDS = [
//   'javascript',
//   'react',
//   'reactjs',
//   'angular',
//   'html',
//   'css',
//   'framework',
//   'frameworks',
//   'jqurey',
//   'object',
//   'functional',
//   'develop',
//   'python',
//   'c#',
//   'c++',
//   'c',
//   'typescript',
//   'rust',
//   'java',
//   'php',
//   'swift',
//   'sql',
//   'mysql',
//   'nosql',
//   'ruby',
//   'net',
//   'test',
//   'tdd',
//   'node',
//   'nodejs',
//   'algorithm',
//   'boolean',
//   'variable',
//   'program',
//   'argument',
//   'ascii',
//   'bug',
//   'code',
//   'conditional',
//   'data',
//   'loop',
//   'pointer',
//   'language',
//   'backend',
//   'back-end',
//   'frontend',
//   'front-end',
//   'server',
//   'syntax',
//   'go',
//   'sass',
//   'cobol',
//   'kotlin',
//   'android',
//   'apple',
//   'visual',
//   'git',
//   'bash',
//   'gitbash',
//   'git-bash',
//   'github',
//   'git-hub',
//   'client',
//   'skill',
//   'build',
//   'building',
//   'configure',
//   'diverse',
//   'diversity',
//   'integrity',
//   'benefit',
//   'accountable',
//   'linux',
//   'windows',
//   'mac',
//   'macos',
//   'web',
//   'command',
//   'communication',
//   'communicate',
//   'network',
//   'troubleshoot',
//   'troubleshooting',
//   'vue.js',
//   'vuejs',
//   'sproutcore',
//   'oriented',
//   'object-oriented',
//   'keynote',
//   'ui',
//   'ux',
//   'stakeholders',
//   'async',
//   'asynchronous',
//   'tests',
//   'firefox',
//   'chrome',
//   'safari',
//   'collaborate',
//   'empathy',
//   'api',
//   'aws',
//   'ubuntu',
//   'jira',
//   'spec',
//   'migration',
//   'maintain',
//   'jenkins',
//   'teamcity',
//   'mongo',
//   'mongodb',
//   'restful',
//   'maven',
//   'soap',
//   'jboss',
//   'weblogic',
//   'websphere',
//   'oracle',
//   'cloud',
//   'cloudbased',
//   'design',
//   'blockchain',
//   'pair-programming',
// ];

export const KEYWORDS = [
  'javascript',
  'react',
  'angular',
  'html',
  'css',
  'framework',
  'jqurey',
  'object',
  'functional',
  'develop',
  'python',
  'c#',
  'c++',
  'c',
  'typescript',
  'rust',
  'java',
  'php',
  'swift',
  'sql',
  'mysql',
  'nosql',
  'ruby',
  'net',
  'test',
  'tdd',
  'nodejs',
  'algorithm',
  'variable',
  'program',
  'argument',
  'ascii',
  'bug',
  'code',
  'conditional',
  'data',
  'pointer',
  'backend',
  'frontend',
  'server',
  'syntax',
  'go',
  'sass',
  'cobol',
  'kotlin',
  'android',
  'apple',
  'visual',
  'github',
  'gitlab',
  'client',
  'build',
  'configure',
  'diverse',
  'integrity',
  'accountable',
  'linux',
  'windows',
  'mac',
  'macos',
  'web',
  'command',
  'communicate',
  'network',
  'troubleshoot',
  'vuejs',
  'sproutcore',
  'oriented',
  'oop',
  'keynote',
  'ui',
  'ux',
  'stakeholder',
  'async',
  'collaborate',
  'empathy',
  'api',
  'aws',
  'ubuntu',
  'jira',
  'spec',
  'migration',
  'maintain',
  'jenkins',
  'teamcity',
  'mongodb',
  'restful',
  'maven',
  'soap',
  'jboss',
  'weblogic',
  'websphere',
  'oracle',
  'cloud',
  'design',
  'blockchain',
  'pair-programming',
  'firebase',
  'graphql'
];